Ui tests
filipmihal/WebJokeApp pull request #1
Opened 2017-08-03 14:35 UTC by filipmihal

I created simple ui test for testing the categories

2017-08-03 20:04 UTC, filipmihal commented
test

2017-08-04 05:42 UTC, ochronus requested changes

2017-08-04 05:42 UTC, ochronus commented on ui_test.py
> +        category = Category.query.order_by(func.random()).first()
It looks like you're reimplementing the whole pagination logic here - one version is already in the view function. It'd make sense to factor this logic out to some kind of 'utils' or 'helpers' python file and reuse the code.

2017-08-04 05:42 UTC, ochronus commented on ui_test.py
> +        url = "http://localhost:5000" + category_url + "?page=" + current_page_num
Instead of hardcoding the local port set it in a config variable

2017-08-04 05:42 UTC, ochronus commented on ui_test.py
> +        category = Category.query.order_by(func.random()).first()
Also you could write a real unit test to test that helper function!

2017-08-04 10:00 UTC, ochronus reviewed
👍

2017-08-04 10:01 UTC, ochronus commented on config.py
> +pagination_framework = 'foundation'
Minor comments, feel free to ignore: config variables are in capitals by convention
Also another convention: have a newline at the end of python files

2017-08-07 10:25 UTC, ochronus commented
Any plans on closing this PR?

2017-08-07 10:46 UTC, merged